### ISSUE TITLE
HTTP::Request object doesn't encode host and path

### ISSUE THREAD

**Issue by ruoso** [tony-o/perl6-http-server#3]
An HTTP Request is formed as:

```
GET /path/to/resource HTTP/1.1
Host: foo.example.com
...
```

The current role offers just an `uri` parameter which I suspect is meant to represent "http://foo.example.com/path/to/resource".

The additional problem is that this also makes other assumptions that cannot be represented in the request by itself, and that includes 1) whether the protocol is `http` or `https` and 2) which port should the uri be. Those two things need to be injected from the application (specially because of reverse proxies).

**Comment by JJ** [comment]
Doesn't what? Sorry, I am too late, but still...

**Comment by ruoso** [comment]
> Doesn't what? Sorry, I am too late, but still...

An HTTP request doesn't just take an URI to make the request. An User Agent may more commonly use an URI as the starting point of how to make the request, but the actual request actually needs to encode it differently.

Specifically, an HTTP request is made to a particular path in a particular host, rather than on a URI specifically. For instance, the specific transport (being tunneled over SSL or not) is not a part of the actual request, there's a decoupling from the "request/response" coreography from the transport on which the request is made.

**Comment by lizmat** [comment]
The `HTTP::Request::Role` role just has an `uri` attribute.  It is up to the consumer to make sure the attribute is used correctly.  So this is not in realm of this role, but appears to be a bug of an implementation.  So closing.  Please re-open if you disagree.
