### ISSUE TITLE
What to do with this

### ISSUE THREAD

**Issue by JJ** [tony-o/perl6-http-server#4]
This module is not released in the ecosystem, yet there are a couple of other modules that depend on it. We can 
* Release this
* Deprecate this

Or do something about this...

**Comment by AlexDaniel** [comment]
Given that things depend on it, just add it to the ecosystem?

**Comment by AlexDaniel** [comment]
Also, should we move it to perl6-community-modules before doing that?

**Comment by jonathanstowe** [comment]
Definitely move it community modules, definitely add it to ecosystem.

**Comment by AlexDaniel** [comment]
We're now in perl6-community-modules. Please add it to the ecosystem (and edit META6.json to point to the right repo).

**Comment by JJ** [comment]
@AlexDaniel no problem with that, but what's the difference between the perl6 orga and the perl6-community-modules orga? Apart from the people involved...

**Comment by JJ** [comment]
@jonathanstowe as long as we're releasing it, should we maybe change names? Role::HTTP::Response, for instance? To avoid the name clashes.

**Comment by JJ** [comment]
It was apparently released, only the source-url was wrong and then it couldn't be found. So who knows...

**Comment by JJ** [comment]
maybe call the module HTTP::Roles and have "Role" as a suffix. What do you think?

**Comment by tony-o** [comment]
I'm agreeable to `HTTP::Roles` with `HTTP::Server::Role, HTTP::Response::Role, etc.`.  The other modules that depend on this should be combed for so we don't break.

**Comment by JJ** [comment]
Reverse dependencies are in #5

**Comment by tony-o** [comment]
@jj did you release?  if so please close this issue
